    // Test if a java exception can be thrown from the callback.
    @Test
    public void callWithLock_throwInCallback() {
        RealmConfiguration config = configFactory.createConfiguration();
        final RuntimeException exception = new RuntimeException();

        try {
            OsObjectStore.callWithLock(config, new Runnable() {
                @Override
                public void run() {
                    throw exception;
                }
            });
            fail();
        } catch (RuntimeException e) {
            assertEquals(exception, e);
        }

        // The lock should be released after exception thrown
        final AtomicBoolean callbackCalled = new AtomicBoolean(false);
        assertTrue(OsObjectStore.callWithLock(config, new Runnable() {
            @Override
            public void run() {
                callbackCalled.set(true);
            }
        }));
    }

