    @Test
    public void currentUser_throwsIfMultipleUsersLoggedIn() {
        RealmObjectServer originalAuthServer = SyncManager.getAuthServer();
        RealmObjectServer authServer = Mockito.mock(RealmObjectServer.class);
        SyncManager.setAuthServerImpl(authServer);

        try {
            // 1. Login two random users
            when(authServer.loginUser(any(SyncCredentials.class), any(URL.class))).thenAnswer(new Answer<AuthenticateResponse>() {
                @Override
                public AuthenticateResponse answer(InvocationOnMock invocationOnMock) throws Throwable {
                    return getNewRandomUser();
                }
            });
            SyncUser.logIn(SyncCredentials.facebook("foo"), "http:/test.realm.io/auth");
            SyncUser.logIn(SyncCredentials.facebook("foo"), "http:/test.realm.io/auth");

            // 2. Verify current() now throws
            try {
                SyncUser.current();
                fail();
            } catch (IllegalStateException ignore) {
            }
        } finally {
            SyncManager.setAuthServerImpl(originalAuthServer);
        }

    }

