    // Tests that Observables keep strong references to their parent, so they are not accidentally GC'ed while
    // waiting for results from the async API's.
    @Test
    @RunTestInLooperThread
    @SuppressWarnings("CheckReturnValue")
    public void dynamicRealmResults_gcStressTest() {
        final int TEST_SIZE = 50;
        final AtomicLong innerCounter = new AtomicLong();
        final DynamicRealm realm = DynamicRealm.getInstance(looperThread.getConfiguration());

        realm.beginTransaction();
        for (int i = 0; i < TEST_SIZE; i++) {
            realm.createObject(AllTypes.CLASS_NAME).set(AllTypes.FIELD_LONG, i);
        }
        realm.commitTransaction();

        for (int i = 0; i < TEST_SIZE; i++) {
            // Doesn't keep a reference to the Observable.
            realm.where(AllTypes.CLASS_NAME).equalTo(AllTypes.FIELD_LONG, i).findAllAsync().asFlowable()
                    .filter(new Predicate<RealmResults<DynamicRealmObject>>() {
                        @Override
                        public boolean test(RealmResults<DynamicRealmObject> results) throws Exception {
                            return results.isLoaded();
                        }
                    })
                    .take(1) // Unsubscribes from Realm.
                    .subscribe(new Consumer<RealmResults<DynamicRealmObject>>() {
                        @Override
                        public void accept(RealmResults<DynamicRealmObject> dynamicRealmObjects) throws Exception {
                            // Not guaranteed, but can result in the GC of other RealmResults waiting for a result.
                            Runtime.getRuntime().gc();
                            if (innerCounter.incrementAndGet() == TEST_SIZE) {
                                realm.close();
                                looperThread.testComplete();
                            }
                        }
                    }, new Consumer<Throwable>() {
                        @Override
                        public void accept(Throwable throwable) throws Exception {
                            fail(throwable.toString());
                        }
                    });
        }
    }

